#include "resource.h"
#include <graphics.h>
IMAGE ascii_1280;
IMAGE ascii_1280_white;
IMAGE title_bk00;
IMAGE title_ch00;
IMAGE title_ch00white;
IMAGE title_logo;
IMAGE title_logowhite;
IMAGE title_item00;
IMAGE title_item00white;
IMAGE front00;
IMAGE front00_white;
IMAGE cloud;
IMAGE imgPlayer00;
IMAGE imgPlayer00white;
IMAGE imgBullet00;
IMAGE imgBullet00white;
IMAGE imgEnemy00;
IMAGE imgEnemy00white;
IMAGE imgEnemy00Flipped;
IMAGE imgEnemy00Flippedwhite;
IMAGE imgEnemyBullet;
IMAGE imgEnemyBulletwhite;
IMAGE imgEnm5;
IMAGE imgEnm5_white;
IMAGE item_;
IMAGE item_white;
const wchar_t* stage01aPath;
const wchar_t* stage01bPath;
const wchar_t* stage01cPath;
const wchar_t* stage01dblackPath;
const wchar_t* ending_bg00Path;
const wchar_t* seTan00Path;
const wchar_t* seEnep00Path;
const wchar_t* seDamage00Path;
const wchar_t* seCardgetPath;
const wchar_t* seItem00Path;
const wchar_t* seOk00Path;
const wchar_t* sePldead00Path;
const wchar_t* sechangeitemPath;
void loadResources()
{
	loadimage(&ascii_1280, _T("ANM/ascii/ascii_1280.png"));
	loadimage(&ascii_1280_white, _T("ANM/ascii/ascii_1280_white.png"));
	loadimage(&title_bk00, _T("ANM/title/title_bk00.png"));
	loadimage(&title_ch00, _T("ANM/title/title_ch00.png"));
	loadimage(&title_ch00white, _T("ANM/title/title_ch00white.png"));
	loadimage(&title_logo, _T("ANM/title/title_logo.png"));
	loadimage(&title_logowhite, _T("ANM/title/title_logowhite.png"));
	loadimage(&title_item00, _T("ANM/title/title_item00.png"));
	loadimage(&title_item00white, _T("ANM/title/title_item00white.png"));
	loadimage(&front00, _T("ANM/front/front00.png"));
	loadimage(&front00_white, _T("ANM/front/front00_white.png"));
	loadimage(&cloud, _T("ANM/background/stage01/st01dwhite.png"));
	loadimage(&imgPlayer00, _T("ANM/player/pl00/pl00.png"));
	loadimage(&imgPlayer00white, _T("ANM/player/pl00/pl00white.png"));
	loadimage(&imgBullet00, _T("ANM/player/pl00/pl00a.png"));
	loadimage(&imgBullet00white, _T("ANM/player/pl00/pl00awhite.png"));
	loadimage(&imgEnemy00, _T("ANM/enemy/enemy.png"));
	loadimage(&imgEnemy00white, _T("ANM/enemy/enemywhite.png"));
	loadimage(&imgEnemy00Flipped, _T("ANM/enemy/enemyFlip.png"));
	loadimage(&imgEnemy00Flippedwhite, _T("ANM/enemy/enemyFlipwhite.png"));
	loadimage(&imgEnemyBullet, _T("ANM/bullet/bullet1.png"));
	loadimage(&imgEnemyBulletwhite, _T("ANM/bullet/bullet1white.png"));

	loadimage(&imgEnm5, _T("ANM/stgenm/stage05/enm5.png"));
	loadimage(&imgEnm5_white, _T("ANM/stgenm/stage05/enm5_white.png"));

	loadimage(&item_, _T("ANM/bullet/item.png"));
	loadimage(&item_white, _T("ANM/bullet/item_white.png"));
	stage01aPath = L"ANM/background/stage01/st01a.png";
	stage01bPath = L"ANM/background/stage01/st01b.png";
	stage01cPath = L"ANM/background/stage01/st01c.png";
	stage01dblackPath = L"ANM/background/stage01/st01dblack.png";
	ending_bg00Path = L"ANM/ending/stbg00.png";
	seTan00Path = L"MUSIC/se_tan00.wav";
	seEnep00Path = L"MUSIC/se_enep00.wav";
	seDamage00Path = L"MUSIC/se_damage00.wav";
	seCardgetPath = L"MUSIC/se_cardget.wav";
	seItem00Path = L"MUSIC/se_item00.wav";
	seOk00Path = L"MUSIC/se_ok00.wav";
	sePldead00Path = L"MUSIC/se_pldead00.wav";
	sechangeitemPath = L"MUSIC/se_changeitem.wav";
}